[package]
name = "evalica"
version = "0.2.0"
edition = "2021"
description = "Evalica, your favourite evaluation toolkit."
repository = "https://github.com/dustalov/evalica"
license = "Apache-2.0"
exclude = ["*.csv", "*.ipynb", "*.svg", ".github", ".gitignore"]
publish = []

[lib]
name = "evalica"
crate-type = ["cdylib"]

[dependencies]
approx = "^0.5.1"
ndarray = "^0.16.1"
num-traits = "^0.2.19"
pyo3 = { version = "^0.22.3", features = ["extension-module", "abi3-py38"], optional = true }
numpy = { git = "https://github.com/PyO3/rust-numpy.git", revision = "ca3299fe260ff247fe45bd667eb4b0fe5cb1acc8", optional = true }

[features]
python = ["dep:pyo3", "dep:numpy"]
