[build-system]
requires = ["maturin>=1.6,<2.0"]
build-backend = "maturin"

[project]
name = "evalica"
license = "Apache-2.0"
requires-python = ">= 3.8"
dependencies = ["numpy>=1.16.0"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Typing :: Typed",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["hypothesis[numpy]", "mypy", "nbqa", "notebook", "pandas", "pytest", "ruff", "twine"]

[tool.maturin]
python-source = "python"

[tool.mypy]
ignore_missing_imports = true
plugins = ["numpy.typing.mypy_plugin"]
strict = true

[tool.nbqa.addopts]
ruff = ["--ignore=B018"]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "FIX002",
    "D100",
    "D103",
    "D104",
    "D203",
    "D212",
    "ERA001",
    "FA102",
    "PLR",
    "PLW",
    "S101",
    "TD002",
    "TD003",
]
