name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  DO_NOT_TRACK: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        # Cargo.lock is in .gitignore, so we use Cargo.toml
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Build
      run: cargo build --verbose
    - name: Run tests (Rust)
      run: cargo test --verbose
    - name: Set up Maturin
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv pip install --system maturin
        maturin develop --uv --extras dev
    - name: Lint with Ruff
      run: ruff check
    - name: Lint with Mypy
      run: mypy .
    - name: Run tests (Python)
      run: python3 -m unittest discover python
    - name: Build with Maturin
      run: maturin build --release --out=dist/
    - name: Check with Twine
      run: twine check --strict dist/*
